training_pipeline_config:
  pipeline_name: Visa
  artifact: artifact





data_ingestion_config:
  dataset_download_url: url(s3,Database,Github)
  raw_data_dir: raw_data
  ingested_dir: ingested_data
  ingested_train_dir: train
  ingested_test_dir: test